name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag for the release"
        required: true
        default: "v1.0.0"

permissions:
  contents: write
  actions: read
  id-token: none

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.203'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish Application
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=true -o publish

      - name: Rename Executable
        run: |
          ren publish\cs2_bhop.exe cs2-bhop.exe

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cs2-bhop
          path: publish/cs2-bhop.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: cs2-bhop
          path: ./artifact-download

      - name: Verify Downloaded Artifact
        run: |
          echo "Listing artifact-download directory:"
          ls -la ./artifact-download
          if [ ! -f ./artifact-download/cs2-bhop.exe ]; then
            echo "Error: File cs2-bhop.exe not found in artifact-download directory!"
            exit 1
          fi

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: cs2-bhop - Release ${{ github.event.inputs.tag_name }}
          body_path: ./ChangeLog.md
          files: |
            ./artifact-download/cs2-bhop.exe
